corda/corda-docs

- .ci/Jenkinsfile.build
Fixed the hostname of Docsite for `publish-*` tags
> Fixed copy & paste mistake

- content/en/docs/cenm/1.2/deployment-kubernetes.md
- highlight that it needs to be **free** for CENM services memory 
- bump up memory to 8 GB
> Update k8s memory requirements

- .ci/Jenkinsfile.build
* removed obsolete getters & setters from Configuration class
* added setup of interactive Artifactory promotion
* all stages connected with publish & deploy as a single stage...
* ...but as sequential stages
also still work in progress!
> Tidying up and interactive Artifactory promotions

- content/en/docs/corda-os/4.3/shell.md
- content/en/docs/corda-os/4.4/shell.md
Refining the issue with InvokeRpc.startTrackedFlowDynamic.
> CORDA-3577 - modifying permissions page

- .ci/Jenkinsfile.build
> Cosmetic changes

- content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
@VCAMP @benpesterr3 @sachingokhale 
This PR picks up on, and replaces PRs #56 and #58.
> [EG-1526] Final release notes for CE 4.2.1 and CE 4.4.1

- content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
As per https://r3-cev.atlassian.net/browse/EG-1441?focusedCommentId=96857
> [EG-1526] Updated CE 4.4.1 version to CE 4.4.2

- themes/hugo-r3-theme/layouts/partials/scripts.html
Allow inline mathjax to render as expected.
> Allow inline mathjax rendering

- content/en/docs/corda-enterprise/3.0/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/3.1/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/3.2/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/3.3/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/4.0/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/4.1/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/4.2/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/4.3/serialization-enum-evolution.md
- content/en/docs/corda-enterprise/4.4/serialization-enum-evolution.md
- content/en/docs/corda-os/3.0/serialization-enum-evolution.md
- content/en/docs/corda-os/3.1/serialization-enum-evolution.md
- content/en/docs/corda-os/3.2/serialization-enum-evolution.md
- content/en/docs/corda-os/3.3/serialization-enum-evolution.md
- content/en/docs/corda-os/3.4/serialization-enum-evolution.md
- content/en/docs/corda-os/4.0/serialization-enum-evolution.md
- content/en/docs/corda-os/4.1/serialization-enum-evolution.md
- content/en/docs/corda-os/4.3/serialization-enum-evolution.md
- content/en/docs/corda-os/4.4/serialization-enum-evolution.md
Made various minor formatting fixes to correct display of code samples.
Changes were made in 4.4, 4.3, 4.2, 41, 4.0, 3.4, 3.3, 3.2, 3.2, 3.1, and 3.0.
> [EG-2001] Fixing formatting issues

- content/en/docs/corda-enterprise/4.4/notary/faq/eta-mechanism.md
- content/en/docs/corda-enterprise/4.4/notary/faq/notary-failover.md
- content/en/docs/corda-enterprise/4.4/notary/faq/notary-load-balancing.md
- content/en/docs/corda-enterprise/4.4/notary/faq/toctree.md
FAQ menu with links to the following topics:
- ETA Mechanism Overview
- Notary Load Balancing
- Notary Failover
> [EG-1933] Added menu structure for /notary/faq section

- content/en/docs/cenm/1.2/upgrade-notes.md
release in the CENM upgrade guide, also made a few improvements to intro para and patch release sections
> [EG-1441] Commenting back in the upgrade notes for CENM 1.2.1 patch

- content/en/docs/cenm/1.2/identity-manager.md
**NO NEED TO PROPAGATE TO 1.3** - already done in https://github.com/corda/corda-docs-develop/pull/375
> [EG-2769] Small fix to `crlFiles` entries in examples in idman page for CENM 1.2

- content/en/docs/cenm/1.2/legal-info.md
- content/en/docs/cenm/1.3/legal-info.md
- content/en/docs/corda-enterprise/4.5/legal-info.md
- content/en/docs/corda-os/4.5/release-checksum-os.md
Added legal info file for CENM 1.3.
> [EG-1457/EG-1584] Updated legal-info files

- content/en/docs/corda-enterprise/4.5/corda-network/UAT.md
- content/en/docs/corda-enterprise/4.5/operations/ops-index.md
- content/en/docs/corda-enterprise/4.5/performance-testing/installation.md
- content/en/docs/corda-enterprise/4.5/performance-testing/introduction.md
- content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-samplers.md
- content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-testplans.md
- content/en/docs/corda-enterprise/4.5/performance-testing/performance-tuning.md
- content/en/docs/corda-enterprise/4.5/performance-testing/practical-considerations.md
- content/en/docs/corda-enterprise/4.5/performance-testing/r3-performance-runs.md
- content/en/docs/corda-enterprise/4.5/performance-testing/running-jmeter-corda.md
- content/en/docs/corda-enterprise/4.5/performance-testing/toc-tree.md
- content/en/docs/corda-os/4.5/corda-network/UAT.md
- content/en/docs/corda-os/4.5/corda-network/corda-network-foundation.md
Added menu option and navigation for Performance Testing section.
> [EG-1206/EG-1209] Fix menu: check for missing menu entries of existing pages

- content/en/docs/corda-enterprise/4.4/node/setup/host-prereq.md
- content/en/docs/corda-enterprise/4.5/node/setup/host-prereq.md
> EG-1269 - fix tables in node setup prerequisites Ent 4.4 

- content/en/docs/corda-enterprise/4.4/notary/hsm-support.md
- content/en/docs/corda-enterprise/4.5/notary/hsm-support.md
- content/en/docs/corda-os/4.5/release-notes.md
* [EG-3148] Fixed a bad link in OS 4.5 release notes
* [EG-3149] Fixed a typo in HSM notaries page for CE 4.4 and CE 4.5
> [EG-3148] Fixed a bad link in OS 4.5 release notes

- content/en/docs/corda-enterprise/4.5/node/deploy/one-click-deployment.md
I have used `{{< figure src="image.png" width="100px"}}>` to reduce the size of the images.
This is not ideal, because it is mixing Markdown and Hugo shortcodes, which is something I feel we should keep to an absolute minimum. However it did solve the problem.
> EG-3169: changing size of images

- content/en/docs/cenm/1.3/legal-info.md
Fixed small issue with some lines showing up as heavy weight when viewed on docs staging, while other lines showed up as normal weight.
> [EG-1457/EG-1584] Update legal-info files

- content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Fixed bullet for the point "We have fixed an issue where Level.WARN and Level.FATAL logs".
> [EG-1572/EG-3207] Minor formatting glitch in Fixed issues section

- content/en/docs/corda-enterprise/4.5/platform-support-matrix.md
@thschroeter does this change look correct to satisfy this: https://r3-cev.atlassian.net/browse/EG-3200
> EG-3200: Adding details for notary implementations of HSMs

- .ci/algolia/configure_index_by_rest.py
After we've set the facets on the algolia index,
query them to make sure they're set.
> Report broken crawl.

- content/en/docs/corda-enterprise/4.4/node/operating/clientrpc.md
- content/en/docs/corda-enterprise/4.5/node/operating/clientrpc.md
Added missing code sample and fixed broken links.
> [EG-1572/EG-3592] Missing code sample and broken links in Interacting with a node

- content/en/docs/corda-enterprise/4.4/corda-network/setup-segregated-notary.md
- content/en/docs/corda-enterprise/4.5/corda-network/setup-segregated-notary.md
Adding the document to Enterprise 4.4 for review, upon feedback, will add commits for 4.5.
> EG-1677: Segregated network documentation for the Corda Network

- content/en/docs/corda-enterprise/4.0/node-database.md
- content/en/docs/corda-enterprise/4.2/node-database-admin.md
- content/en/docs/corda-enterprise/4.3/node-database-admin.md
- content/en/docs/corda-enterprise/4.4/node/operating/node-database-admin.md
- content/en/docs/corda-enterprise/4.5/node/operating/node-database-admin.md
I have updated the SQL script described in https://r3-cev.atlassian.net/browse/EG-3648. I have also update the corresponding scripts in the 4.0, 4.2, 4.3, and 4.4 documentation. Note: the script didn't seem to exist in the 4.1 documentation, so no change has been made there.
> EG-3648: adding GO statement to Azure SQL scripts

- content/en/docs/corda-enterprise/4.0/corda-testnet-intro.md
- content/en/docs/corda-enterprise/4.1/corda-testnet-intro.md
- content/en/docs/corda-enterprise/4.2/corda-testnet-intro.md
- content/en/docs/corda-enterprise/4.3/corda-testnet-intro.md
- content/en/docs/corda-enterprise/4.4/network/corda-testnet-intro.md
- content/en/docs/corda-enterprise/4.5/network/corda-testnet-intro.md
- content/en/docs/corda-os/4.0/corda-testnet-intro.md
- content/en/docs/corda-os/4.1/corda-testnet-intro.md
- content/en/docs/corda-os/4.3/corda-testnet-intro.md
- content/en/docs/corda-os/4.4/corda-testnet-intro.md
- content/en/docs/corda-os/4.5/corda-testnet-intro.md
EG-3723 Updated Corda Testnet Intro pages for OS and CE 4.0 and above.
Related PRs: 
https://github.com/corda/corda/pull/5734
https://github.com/corda/corda-docs-develop/pull/478
https://github.com/corda/corda-docs-develop/pull/483
> EG-3723 Updated Corda Testnet Intro pages for OS and CE 4.0 and above

- content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
- content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
- content/en/docs/corda-os/4.4/tutorial-cordapp.md
- content/en/docs/corda-os/4.5/tutorial-cordapp.md
Added Kotlin instructions and fixed links across CE and OS 4.4 and 4.5.
> EG-3661 Add Kotlin instructions on Running a sample CorDapp page

- content/en/docs/corda-enterprise/4.0/upgrading-cordapps.md
- content/en/docs/corda-enterprise/4.2/upgrading-cordapps.md
- content/en/docs/corda-enterprise/4.3/upgrading-cordapps.md
- content/en/docs/corda-enterprise/4.4/cordapps/upgrading-cordapps.md
- content/en/docs/corda-enterprise/4.5/cordapps/upgrading-cordapps.md
- content/en/docs/corda-os/4.3/upgrading-cordapps.md
- content/en/docs/corda-os/4.4/upgrading-cordapps.md
- content/en/docs/corda-os/4.5/upgrading-cordapps.md
EG-2735 Removed duplicate serialisation section from multiple versions
> EG-2735 Removed duplicate serialisation section from multiple versions

- content/en/docs/corda-enterprise/3.0/api-testing.md
- content/en/docs/corda-enterprise/3.1/api-testing.md
- content/en/docs/corda-enterprise/3.2/api-testing.md
- content/en/docs/corda-enterprise/3.3/api-testing.md
- content/en/docs/corda-enterprise/4.0/api-testing.md
- content/en/docs/corda-enterprise/4.1/api-testing.md
- content/en/docs/corda-enterprise/4.2/api-testing.md
- content/en/docs/corda-enterprise/4.3/api-testing.md
- content/en/docs/corda-enterprise/4.4/cordapps/api-testing.md
- content/en/docs/corda-enterprise/4.5/cordapps/api-testing.md
- content/en/docs/corda-os/3.0/api-testing.md
- content/en/docs/corda-os/3.1/api-testing.md
- content/en/docs/corda-os/3.2/api-testing.md
- content/en/docs/corda-os/3.3/api-testing.md
- content/en/docs/corda-os/3.4/api-testing.md
- content/en/docs/corda-os/4.0/api-testing.md
- content/en/docs/corda-os/4.1/api-testing.md
- content/en/docs/corda-os/4.3/api-testing.md
- content/en/docs/corda-os/4.4/api-testing.md
- content/en/docs/corda-os/4.5/api-testing.md
EG-2800 Removed redundant sentence in API Testing page - all versions up to CE/OS 4.5
> EG-2800 Removed redundant sentence in API Testing page - all versions up to CE/OS 4.5

- content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
EG-2091 Fixed a link in CE 4.4 enterprise release notes, and updated a reference to upgrade guide in Known Issues section
> EG-2091 Fixed a link in CE 4.4 enterprise release notes

- content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
- content/en/docs/corda-os/4.4/app-upgrade-notes.md
EG-1451 Updated "CorDapps to newer Platform Versions" pages in OS 4.4 and CE 4.4 with a platform version matrix section and a note about upgrading apps to PV 6
> EG-1451 Updated "CorDapps to newer Platform Versions" pages in OS/CE 4.4

- content/en/docs/corda-enterprise/4.0/performance-testing/running-jmeter-corda.md
- content/en/docs/corda-enterprise/4.1/performance-testing/running-jmeter-corda.md
- content/en/docs/corda-enterprise/4.2/performance-testing/running-jmeter-corda.md
- content/en/docs/corda-enterprise/4.3/performance-testing/running-jmeter-corda.md
- content/en/docs/corda-enterprise/4.4/performance-testing/running-jmeter-corda.md
EG-2592 Fixed a typo in Running JMeter page for CE 4.0 to 4.4
> EG-2592 Fixed a typo in Running JMeter page for CE 4.0 to 4.4

- content/en/docs/corda-enterprise/4.1/checkpoint-tooling.md
- content/en/docs/corda-enterprise/4.2/checkpoint-tooling.md
- content/en/docs/corda-enterprise/4.3/checkpoint-tooling.md
- content/en/docs/corda-enterprise/4.4/checkpoint-tooling.md
- content/en/docs/corda-enterprise/4.5/checkpoint-tooling.md
EG-3905 Fixed typo in checkpoint tooling pages for CE 4.1 - 4.5
> EG-3905 Fixed typo in checkpoint tooling pages for CE 4.1 - 4.5

- content/en/docs/corda-enterprise/4.4/notary/installing-the-notary-service.md
- content/en/docs/corda-enterprise/4.5/notary/installing-the-notary-service.md
> EG-2842: Remove references to rewriteBatchedStatements and useSSL

- themes/hugo-r3-theme/layouts/index.html
> EG-4007 Fixed some typos

- themes/hugo-r3-theme/layouts/index.html
EG-4007 Updates to home page strings
> EG-4007 Updates to home page strings

- themes/hugo-r3-theme/layouts/index.html
> EG-4007 Fixed a link

- content/en/docs/cenm/1.4/release-notes.md
EG-3240-2 Updated Known Issues in CENM 1.4 release notes as per feedback [part 1]
> EG-3240-2 Updated Known Issues in CENM 1.4 release notes as per feedback [part 1]

- content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
EG-4013 Fixed broken links in CE 4.6 release notes
> EG-4013 Fixed broken links in CE 4.6 release notes

- content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
- content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-file.md
- content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
- content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-file.md
EG-4014 EG-3934 Added notary serviceLegalName info to node configuration fields page and consolidated latest node conf content for 4.6 in the ops guide pages
> EG-4014 EG-3934 Added notary serviceLegalName info + ops guide updates

- content/en/robots.txt
EG-3361 Updated robots.txt for new release
> EG-3361 Updated robots.txt for new release

- content/en/docs/cenm/1.4/signing-service.md
EG-4033 Removed empty duplicate serviceLocation entry in Signing Service page for CENM 1.4
> EG-4033 Removed empty duplicate serviceLocation entry in Signing Service page for CENM 1.4

- content/en/docs/corda-enterprise/4.6/notary/notary-monitoring.md
- content/en/docs/corda-enterprise/4.6/operations/monitoring-logging/metrics-monitoring-scenarios.md
> EG-3516: Typo fixes

- content/en/docs/cenm/1.3/release-notes.md
- content/en/docs/cenm/1.4/release-notes.md
> EG-4063: Fixing some links that shouldn't be links

- content/en/docs/corda-enterprise/4.4/node/operating/node-database-admin.md
- content/en/docs/corda-enterprise/4.5/node/operating/node-database-admin.md
- content/en/docs/corda-enterprise/4.6/node/operating/node-database-admin.md
EG-4099 Fixed anchor links in Node Database Admin page for CE 4.4, 4.5, and 4.6
> EG-4099 Fixed anchor links in Node Database Admin page for CE 4.4, 4.5, and 4.6

- content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
- content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
EG-4110 Fixed db migration steps in CE 4.6 upgrade guide
> EG-4110 Fixed db migration steps in CE 4.6 upgrade guide

- content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
> EG-4110 Fixed bad link

- content/en/docs/corda-enterprise/4.5/cordapps/token-diamond-example.md
- content/en/docs/corda-enterprise/4.6/cordapps/token-diamond-example.md
- content/en/docs/corda-os/4.5/token-diamond-example.md
- content/en/docs/corda-os/4.6/token-diamond-example.md
> EG-4122: Fixing code block bug in token sdk example

- content/en/docs/corda-os/4.6/hello-world-flow.md
- content/en/docs/corda-os/4.6/hello-world-introduction.md
- content/en/docs/corda-os/4.6/hello-world-running.md
- content/en/docs/corda-os/4.6/hello-world-state.md
- content/en/docs/corda-os/4.6/hello-world-template.md
Tested, reviewed, and updated content. Made changes according to feedback from QA.
> EG-3265: Tested, reviewed, and updated content in Hello World! tutorial.

- themes/hugo-r3-theme/layouts/index.html
> EG-4148: Add APIs tab to homepage.

- content/en/docs/corda-os/4.4/hello-world-flow.md
- content/en/docs/corda-os/4.4/hello-world-introduction.md
- content/en/docs/corda-os/4.4/hello-world-running.md
- content/en/docs/corda-os/4.4/hello-world-state.md
- content/en/docs/corda-os/4.4/hello-world-template.md
- content/en/docs/corda-os/4.5/hello-world-flow.md
- content/en/docs/corda-os/4.5/hello-world-introduction.md
- content/en/docs/corda-os/4.5/hello-world-running.md
- content/en/docs/corda-os/4.5/hello-world-state.md
- content/en/docs/corda-os/4.5/hello-world-template.md
Tested, reviewed, and updated Hello, World! Tutorial in OS 4.4, 4.5. Changes already made in 4.6.
> EG-3265: Tested, reviewed, and updated Hello, World! Tutorial in OS 4.4, 4.5.

- themes/hugo-r3-theme/layouts/index.html
EG-1629 Updating search config for home page to include CDL content
> EG-1629 EG-4161 Updating search config for home page to include CDL content

- content/en/docs/corda-enterprise/4.6/legal-info.md
- content/en/docs/corda-os/4.6/legal-info.md
Split from #297 for easier reviewing.
> EG-4165 Update 4.6 OS & Ent New Relic licences

- content/en/docs/corda-enterprise/4.6/network/corda-testnet-intro.md
submitted a PR just to fix this small issue
> EG-4205 Removing loose bracket in CE 4.6/4.6 testnet intro page

- content/en/docs/corda-enterprise/4.5/docker-image.md
- content/en/docs/corda-enterprise/4.6/docker-image.md
- content/en/docs/corda-os/4.5/docker-image.md
- content/en/docs/corda-os/4.6/docker-image.md
> [EG-4375] Updating version reference in a command

- content/en/docs/corda-enterprise/4.4/_index.md
- content/en/docs/corda-enterprise/4.5/_index.md
- content/en/docs/corda-enterprise/4.6/_index.md
I've done two things:
* Replaced the ticks and crosses in boxes with ticks and crosses that aren't in boxes
* Centered the text in the columns with ticks and crosses.
> EG-1619: improving layout of comparison matrices

- content/en/docs/corda-enterprise/3.3/release-notes.md
- content/en/docs/corda-enterprise/4.0/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.1/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
EG-4597 Fixed links in upgrade recommendation sections of CE patch release notes
> EG-4597 Fixed links in upgrade recommendation sections of CE patch release notes

- content/en/docs/corda-os/4.3/node-operations-upgrade-cordapps.md
- content/en/docs/corda-os/4.4/node-operations-upgrade-cordapps.md
- content/en/docs/corda-os/4.5/node-operations-upgrade-cordapps.md
- content/en/docs/corda-os/4.6/node-operations-upgrade-cordapps.md
> EG-4601: Rearranging text and correcting link.

- content/en/docs/cenm/1.5/auth-service.md
- content/en/docs/cenm/1.5/config-database.md
> EG-4638: Adding lockResolutionStrategy config option

- prod/etc/nginx/conf.d/default.conf
EG-4050 Updated nginx redirection to point to the latest doc versions after Q4 2020 doc release
> EG-4050 Updated nginx redirection to point to the latest doc versions after Q4 2020 doc release

- content/en/docs/apps/bankinabox/_index.md
EG-4056 Fix for BIAB version used in search
> EG-4056 Fix for BIAB version used in search

- content/en/docs/corda-enterprise/4.7/cordapps/reissuing-states.md
- content/en/docs/corda-os/4.7/reissuing-states.md
EG-4494 Updated state reissuance pages
> EG-4494 Updated state reissuance pages

- content/en/docs/apps/bankinabox/back-end-guide.md
- content/en/docs/cdl/cdl/cdl-to-code/states-and-statuses.md
- content/en/docs/cenm/1.2/_index.md
- content/en/docs/cenm/1.5/tools-index.md
- content/en/docs/corda-enterprise/4.6/cordapps/cordapp-constraint-migration.md
- content/en/docs/corda-enterprise/4.6/notary/installing-the-notary-service.md
- content/en/docs/corda-enterprise/4.6/upgrading-cordapp.md
- content/en/docs/corda-enterprise/4.7/cordapps/reissuing-states.md
- content/en/docs/corda-enterprise/4.7/network/business-network-membership.md
- content/en/docs/corda-enterprise/4.7/node/archiving/archiving-setup.md
- content/en/docs/corda-enterprise/4.7/notary/installing-the-notary-service.md
- content/en/docs/corda-enterprise/4.7/operations/deployment/cenm-upgrade.md
- content/en/docs/corda-enterprise/4.7/operations/deployment/env-prod-test.md
- content/en/docs/corda-enterprise/4.7/upgrading-cordapp.md
- content/en/docs/corda-os/4.6/node-operations-upgrade-cordapps.md
- content/en/docs/corda-os/4.6/shell.md
- content/en/docs/corda-os/4.7/node-operations-upgrade-cordapps.md
- content/en/docs/corda-os/4.7/shell.md
> EG-4102: Fix broken links

- content/en/docs/corda-os/4.7/core-tutorials-index.md
> Quick fix for links in tables

- content/en/docs/apps/bankinabox/bank-index.md
> Bank in a box index alias addition

- content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
- content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
- content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
- content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
Fixed link in the step 9 Important note and replaced JARs with .jar files
> EG-2092-1: Fixed additional issues in app-upgrade-notes.md

- themes/hugo-r3-theme/package.json
DOC-1840 Added elliptic as a dependency in r3 hugo theme
> DOC-1840 Added elliptic as a dependency in r3 hugo theme

- content/en/docs/corda-os/4.7/hello-world-running.md
- content/en/docs/corda-os/4.7/tutorial-cordapp.md
cc @peterli-r3 
The sample and template all updated a bit.... Here are some of the problems I found. Please review your tutorials....
> Several fixes

- content/en/docs/cenm/1.5/_index.md
- content/en/docs/cenm/1.5/aws-deployment-postgressql.md
- content/en/docs/cenm/1.5/cenm-cli-tool.md
- content/en/docs/cenm/1.5/cenm-console.md
- content/en/docs/cenm/1.5/cenm-error-codes.md
- content/en/docs/cenm/1.5/cenm-support-matrix.md
- content/en/docs/cenm/1.5/config-network-parameters.md
- content/en/docs/cenm/1.5/database-set-up.md
- content/en/docs/cenm/1.5/deployment-kubernetes-auth.md
- content/en/docs/cenm/1.5/deployment-kubernetes-gateway.md
- content/en/docs/cenm/1.5/deployment-kubernetes.md
- content/en/docs/cenm/1.5/quick-start.md
- content/en/docs/cenm/1.5/signing-service.md
- content/en/docs/cenm/1.5/tools-index.md
- content/en/docs/cenm/1.5/updating-network-parameters.md
- content/en/docs/cenm/1.5/user-admin.md
- content/en/docs/cenm/1.5/zone-service.md
- content/en/docs/corda-enterprise/4.7/node/auth-service.md
- content/en/docs/corda-enterprise/4.7/node/gateway-service.md
DOC-1871 Updating some links in CENM 1.5 doc set to point to the latest 4.8 doc pages.
> DOC-1871 Updating some links in CENM 1.5 doc set to point to the latest 4.8 doc pages.

- content/en/docs/cenm/1.5/_index.md
- content/en/docs/corda-enterprise/4.7/_index.md
- content/en/docs/corda-os/4.7/_index.md
- content/en/docs/corda-os/4.8/_index.md
DOC-935 Reordering of LHS menu for 4.8 release
> DOC-935 Reordering of LHS menu for 4.8 release

- content/en/docs/corda-enterprise/4.8/node-metrics.md
> DOC-2022: Removing escape characters from node doc

- content/en/docs/corda-enterprise/4.8/cordapps/tutorial-cordapp.md
- content/en/docs/corda-os/4.8/tutorial-cordapp.md
Propagate fixes to 'running a sample cordapp' to version 4.8
> DOC 1884 add fixes to version 4.8
