corda/corda-docs

- .ci/Jenkinsfile.build
* builds of master branch deployed to docs-staging.corda.net
* builds of tags started with `publish-` deployed to docs.corda.net
* anything else could be deployed to docs-staging
> Switched to the new branch schema

- .github/CODEOWNERS
* see https://help.github.com/en/articles/about-code-owners
* Technical Writers own everything...
* ...except for Jenkins and Github settings (for now)
> Introducing code owners

- content/en/docs/corda-enterprise/4.3.1/corda-configuration-file.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/backup-restore.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/db-guidelines.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/faq/eta-mechanism.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/faq/notary-failover.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/faq/notary-load-balancing.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/faq/toctree.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/ha-notary-service-overview.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/ha-notary-service-setup.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/handling-flag-days.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/hsm-support.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/installing-jpa.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/installing-percona.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/installing-the-notary-service-bootstrapper.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/installing-the-notary-service.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/notary-db-migration.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/notary-metrics.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/notary-sizing.md
- content/en/docs/corda-enterprise/4.3.1/running-a-notary-cluster/upgrading-the-ha-notary-service.md
Add notary docs back into the main menu - they were completely missing.
Fixed a bunch of typos and broken links in the notary docs.
Fix the corda-config file again.  See 'current' version here:  https://docs.corda.net/docs/corda-enterprise/4.3.1/corda-configuration-file.html#configuration-file-fields vs screenshot (see 
https://docs-preview.corda.net/docs/corda-enterprise/4.3.1/corda-configuration-file.html#configuration-file-fields 
when built).
> Fix up broken notary docs in enterprise 4.3.1

- content/en/docs/corda-enterprise/4.3/quickstart-index.md
- content/en/docs/corda-enterprise/4.4/cordapps/quickstart-index.md
- content/en/docs/corda-os/4.1/quickstart-index.md
- content/en/docs/corda-os/4.3/quickstart-index.md
- Doc incorrectly specified Java 8 *JVK*. Changed to Java 8 *JDK*.
> EG-1589: Fixing a typo across a couple of versions.

- content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
- content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Updated latest doc index links in both files and moved the single fixed issue in 4.2.1 from a bullet point to a normal para.
> [EG-1526] Final release notes for CE 4.2.1 and CE 4.4.1 - more fixes

- content/en/docs/corda-os/4.4/serialization-enum-evolution.md
Fixing up formatting in enum evolution page only for OS 4.4.
Removed lots of unused code tabs since there's only kotlin code in the examples.
> EG-1572 Fix up formatting in enum evolution page

- content/en/docs/corda-os/4.0/node-database.md
- content/en/docs/corda-os/4.1/node-database.md
- content/en/docs/corda-os/4.3/node-database.md
- content/en/docs/corda-os/4.4/node-database.md
Inaccurate information removed from Corda OS 4.4, 4.3, 4.1, and 4.0. It did not appear in older versions.
> EG-2463 Removing Inaccurate SQLServer information

- content/en/docs/corda-enterprise/4.3/tutorial-cordapp.md
- content/en/docs/corda-os/4.3/tutorial-cordapp.md
Curl command has been updated as follows to reference Party B, located in New York, country US:
'http://localhost:50005/api/example/create-iou?iouValue=12&partyName=O=PartyB,L=New%20York,C=US'
> [EG-1600] Fixed curl command in Creating an IOU via the endpoint section

- content/en/docs/corda-enterprise/4.3/quickstart-build.md
- content/en/docs/corda-enterprise/4.4/cordapps/quickstart-build.md
- content/en/docs/corda-os/4.1/quickstart-build.md
- content/en/docs/corda-os/4.3/quickstart-build.md
Corda Enterprise 4.4: Changed "input" to "output" in line 204.
Corda Enterprise 4.3: Changed "input" to "output" in line 226.
Corda OS 4.3: Changed "input" to "output" in line 226.
Corda OS 4.1: Changed "input" to "output" in line 223.
> [EG-1518] Changed incorrect references to "input" to refer to"output"

- content/en/docs/corda-enterprise/4.1/release-notes.md
Fixed broken link to Corda Enterprise 4 Enhancements document on R3 website which appeared at the start of the second paragraph in the Corda Enterprise 4.1 release notes.
> [EG-1599]  Fix formatting and broken link in CE release notes for 4.1

- content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
- content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
- content/en/docs/corda-os/4.4/tutorial-cordapp.md
- content/en/docs/corda-os/4.5/tutorial-cordapp.md
Implemented edits for tutorial-cordapp.md for Corda OS 4.4/4.5 and Corda Enterprise 4.4/4.5:
1. Updated the Java server start message and changed the message to code format.
2. Updated the project structure diagram to reflect file structure in the new samples-java repo.
3. Updated the node structure diagram to reflect node structure in the Basic cordapp-example.
> [EG-1572/EG-2080] [Docs] Update CorDapp quickstart and dev pages

- content/en/docs/corda-enterprise/4.5/node/deploy/oneclick-developer-test-environment.md
* Links to new templates repo
* Pulls info on node interaction into new section
* Documents resulting node set-up
* Documents nodes are deployed onto AKS
* Deletes "dev" terminology, to be agnostic
* Fixes typos
> Update to One-Click Deployment Page

- prod/etc/nginx/conf.d/default.conf
Please test locally:
```
make DOCKER_BUILD_ARGS="-e HUGO_BASEURL=\"http://localhost:8888\"" prod-docker-serve
```
and also deploy to staging and test there.
Any URL with out a version, in ent, os, cenm, will redirect to 4.5/4.5/1.3   *regardless of whether it exists*.
http://localhost:8888/docs/corda-enterprise/node-upgrade-notes.html
will go to 4.5
http://localhost:8888/docs/corda-enterprise/nonsense.html
will end up on the 404 page.
> EG-1143 Redirect version-less urls to latest

- content/en/docs/corda-enterprise/4.4/corda-network/UAT.md
- content/en/docs/corda-enterprise/4.4/corda-network/the-corda-network.md
- content/en/docs/corda-enterprise/4.4/cordapps/cordapp-constraint-migration.md
- content/en/docs/corda-enterprise/4.5/cordapps/cordapp-constraint-migration.md
- content/en/docs/corda-os/4.4/corda-network/UAT.md
- content/en/docs/corda-os/4.4/corda-network/the-corda-network.md
Added new menu items for:
Corda Network Foundation
Corda Network Pre-Production Environment
Also fixed broken links to CorDapp constraints migration page (https://docs.corda.net/docs/corda-os/4.4/cordapp-constraint-migration.html) as per ticket.
Fixed additional broken links and migration artifacts (spacing issues, imported ">" signs).
> [EG-1143/EG-1929] UAT page is missing from Corda OS & CE 4.4 menus

- content/en/docs/corda-os/3.3/blob-inspector.md
- content/en/docs/corda-os/3.4/blob-inspector.md
- content/en/docs/corda-os/4.0/blob-inspector.md
- content/en/docs/corda-os/4.1/blob-inspector.md
- content/en/docs/corda-os/4.3/blob-inspector.md
- content/en/docs/corda-os/4.4/blob-inspector.md
- content/en/docs/corda-os/4.5/blob-inspector.md
Replaced the broken hyperlink in OS 4.5 with a statement along the lines of “The tool is distributed as part of Corda OS 4.5 in the form of runnable .jar. file - corda-tools-blob-inspector-4.5.jar.”
Implemented fix in the following versions:
Corda 4.4
Corda 4.5
Corda 4.6
Corda 4.3
Corda 4.1
Corda 4.0
Corda 3.4
Corda 3.3
> [EG-1572/EG-2033] Blob inspector download here url

- content/en/docs/corda-enterprise/3.0/cordapp-overview.md
- content/en/docs/corda-enterprise/3.1/cordapp-overview.md
- content/en/docs/corda-enterprise/3.2/cordapp-overview.md
- content/en/docs/corda-enterprise/3.3/cordapp-overview.md
- content/en/docs/corda-enterprise/4.0/cordapp-overview.md
- content/en/docs/corda-enterprise/4.1/cordapp-overview.md
- content/en/docs/corda-enterprise/4.2/cordapp-overview.md
- content/en/docs/corda-enterprise/4.3/cordapp-overview.md
- content/en/docs/corda-os/2.0/cordapp-overview.md
- content/en/docs/corda-os/3.0/cordapp-overview.md
- content/en/docs/corda-os/3.1/cordapp-overview.md
- content/en/docs/corda-os/3.2/cordapp-overview.md
- content/en/docs/corda-os/3.3/cordapp-overview.md
- content/en/docs/corda-os/3.4/cordapp-overview.md
- content/en/docs/corda-os/4.0/cordapp-overview.md
- content/en/docs/corda-os/4.1/cordapp-overview.md
- content/en/docs/corda-os/4.3/cordapp-overview.md
- content/en/docs/corda-os/4.4/cordapp-overview.md
- content/en/docs/corda-os/4.5/cordapp-overview.md
Removed incorrect carat symbol across 19 CE/OS versions.
> [EG-1572/EG-3379] Typo on the What is a CorDapp? page

- content/en/docs/corda-enterprise/3.0/node-structure.md
- content/en/docs/corda-enterprise/3.1/node-structure.md
- content/en/docs/corda-enterprise/3.2/node-structure.md
- content/en/docs/corda-enterprise/3.3/node-structure.md
- content/en/docs/corda-enterprise/4.0/node-naming.md
- content/en/docs/corda-enterprise/4.1/node-naming.md
- content/en/docs/corda-enterprise/4.2/node-naming.md
- content/en/docs/corda-enterprise/4.3/node-naming.md
- content/en/docs/corda-enterprise/4.4/node/setup/node-naming.md
- content/en/docs/corda-enterprise/4.5/node/setup/node-naming.md
- content/en/docs/corda-os/2.0/deploying-a-node.md
- content/en/docs/corda-os/3.0/generating-a-node.md
- content/en/docs/corda-os/3.1/generating-a-node.md
- content/en/docs/corda-os/3.2/generating-a-node.md
- content/en/docs/corda-os/3.3/generating-a-node.md
- content/en/docs/corda-os/3.4/generating-a-node.md
- content/en/docs/corda-os/4.0/node-naming.md
- content/en/docs/corda-os/4.1/node-naming.md
- content/en/docs/corda-os/4.3/node-naming.md
- content/en/docs/corda-os/4.4/node-naming.md
- content/en/docs/corda-os/4.5/node-naming.md
Removed multiple instances of unwanted carat symbols across multiple docs versions.
> [EG-1572/EG-3251] Typos on Node identity page

- content/en/docs/corda-enterprise/4.4/node/deploy/env-dev.md
- content/en/docs/corda-enterprise/4.5/node/deploy/env-dev.md
Removed broken link and fixed formatting of Package Ownership section on CE 4.4 and 4.5 env-dev page.
> [EG-1572/EG-1503] Remove link to package ownership 

- .ci/Jenkinsfile.indexing
Follows instructions from https://github.com/corda/corda-docs/blob/master/usage-docs/searching.md and simply runs `make crawl`
Algolia credentials are provided with SHELL environment variables, which are subsequently picked up by `make`
> INFRA-418: Initial version of Algolia crawl

- content/en/docs/corda-enterprise/3.0/api-vault-query.md
- content/en/docs/corda-enterprise/3.1/api-vault-query.md
- content/en/docs/corda-enterprise/3.2/api-vault-query.md
- content/en/docs/corda-enterprise/3.3/api-vault-query.md
- content/en/docs/corda-enterprise/4.0/api-vault-query.md
- content/en/docs/corda-enterprise/4.1/api-vault-query.md
- content/en/docs/corda-enterprise/4.2/api-vault-query.md
- content/en/docs/corda-enterprise/4.3/api-vault-query.md
- content/en/docs/corda-os/3.0/api-vault-query.md
- content/en/docs/corda-os/3.1/api-vault-query.md
- content/en/docs/corda-os/3.2/api-vault-query.md
- content/en/docs/corda-os/3.3/api-vault-query.md
- content/en/docs/corda-os/3.4/api-vault-query.md
- content/en/docs/corda-os/4.0/api-vault-query.md
- content/en/docs/corda-os/4.1/api-vault-query.md
- content/en/docs/corda-os/4.3/api-vault-query.md
- content/en/docs/corda-os/4.4/api-vault-query.md
- content/en/docs/corda-os/4.5/api-vault-query.md
Removed the reference to the Corda tutorials from all CE and OS versions, except CE4.4 and CE4.5, where the reference had already been removed.
> [EG-1572/EG-3393] Update documentation for Vault Query API - missing Spring Data JPA examples

- content/en/docs/corda-enterprise/4.0/tutorial-contract.md
- content/en/docs/corda-enterprise/4.1/tutorial-contract.md
- content/en/docs/corda-enterprise/4.2/tutorial-contract.md
- content/en/docs/corda-enterprise/4.3/tutorial-contract.md
- content/en/docs/corda-os/4.0/tutorial-contract.md
- content/en/docs/corda-os/4.1/tutorial-contract.md
- content/en/docs/corda-os/4.3/tutorial-contract.md
- content/en/docs/corda-os/4.4/tutorial-contract.md
- content/en/docs/corda-os/4.5/tutorial-contract.md
Updated sentence to clarify that `ContractState` is implemented indirectly via `OwnableState`.
> [EG-1572/EG-2371] Documentation: Improve clarity of state example

- content/en/_index.md
- themes/hugo-r3-theme/layouts/index.html
Re-named "Developer Tutorials" button on docs home page to "Corda Training".
> [EG-1572/EG-3609] Re-name Developer Tutorials button to Corda Training

- content/en/docs/corda-enterprise/4.0/debugging-a-cordapp.md
- content/en/docs/corda-enterprise/4.1/debugging-a-cordapp.md
- content/en/docs/corda-enterprise/4.2/debugging-a-cordapp.md
- content/en/docs/corda-enterprise/4.3/debugging-a-cordapp.md
- content/en/docs/corda-enterprise/4.4/cordapps/debugging-a-cordapp.md
- content/en/docs/corda-enterprise/4.5/cordapps/debugging-a-cordapp.md
- content/en/docs/corda-os/4.0/debugging-a-cordapp.md
- content/en/docs/corda-os/4.1/debugging-a-cordapp.md
- content/en/docs/corda-os/4.3/debugging-a-cordapp.md
- content/en/docs/corda-os/4.4/debugging-a-cordapp.md
- content/en/docs/corda-os/4.5/debugging-a-cordapp.md
Fixed links to tutorials.
Also, removed unwanted carat symbols, fixed indentation of steps, added note formats where appropriate, added punctuation.
> [EG-1572/EG-3250] Broken links to tutorials on Debugging a CorDapp page

- content/en/docs/corda-enterprise/4.5/node/node-commandline.md
- content/en/docs/corda-os/4.5/node-commandline.md
Adds a warning alerting users to the unexpected behaviour that occurs when adding arguments before the command and how to mitigate this.
> ENT-5702: Updated command line usage

- content/en/docs/corda-enterprise/4.5/node/deploy/env-prod-test.md
- content/en/docs/corda-enterprise/4.5/operations/deployment/env-prod-test.md
Previously, the docs implied that the trust root should be obtained from R3, but this is only true in the case of the Corda Network.
> EG-3735: Fixes incorrect guidance on obtaining network trust root

- content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
* To avoid a third-party dependency issue, we have reverted the supported H2 Database Engine version to **1.4.197** in Corda Enterprise versions 4.4.3, 4.5.1, and 4.6.
> CORDA-3795 Added a CE 4.6 release note

- content/en/docs/corda-enterprise/4.6/flow-start-with-client-id.md
- content/en/docs/corda-enterprise/4.6/node/operating/clientrpc.md
- content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
EG-3884 Doc updates for COMPLETED, FAILED, or KILLED flows will not be returned in the flow query unless they were started with a CLIENT ID
> EG-3884 Doc updates relating to querying COMPLETED, FAILED, and KILLED flows

- content/en/docs/cenm/1.4/_index.md
- content/en/docs/cenm/1.4/aws-deployment-guide.md
- content/en/docs/cenm/1.4/release-notes.md
- content/en/docs/cenm/1.4/signing-service.md
- content/en/docs/corda-enterprise/4.6/_index.md
- content/en/docs/corda-os/4.6/_index.md
- themes/hugo-r3-theme/layouts/index.html
* Fixed broken link on CE landing page.
* Added release notes sections to all landing pages.
* Fixed wrong SMR link on CENM tab in home page.
* Added missing AWS deployment guide link to CENM tab in the home page.
* Added title to AWS deployment guide index.
* Updated CENM RN title.
> EG-4024 Fixed broken link on CE landing page + other fixes

- content/en/cookie-declaration/_index.md
EG-4137 Added privacy@r3.com email address and contact instruction to cookie declaration as per new legal advice on GDPR requirements after an external consultancy review.
> EG-4137 Added privacy@r3.com email address and contact instruction to cookie declaration

- content/en/docs/corda-enterprise/4.2/legal-info.md
- content/en/docs/corda-enterprise/4.3/legal-info.md
- content/en/docs/corda-enterprise/4.4/legal-info.md
- content/en/docs/corda-enterprise/4.5/legal-info.md
- content/en/docs/corda-os/4.3/legal-info.md
- content/en/docs/corda-os/4.4/legal-info.md
- content/en/docs/corda-os/4.5/legal-info.md
- EG-4165 Added missing licence info for metrics-new-relic in CE 4.4, CE 4.5, OS 4.4, and OS 4.5
- EG-4165 Updated licence info for newrelic-api in CE 4.2-4.5 and OS 4.3-4.5
- Propagation downstream from #299 
- Superseding #297
> EG-4165 Update pre-4.6 OS & Ent New Relic licences

- themes/hugo-r3-theme/layouts/index.html
EG-4038 Fixed broken link on the home page for the CENM 1.4.0 legal info page, added one for CENM 1.4.1, and added a link to the artifacts and checksums page
> EG-4038 Fixed broken link and added new links on the home page for the CENM 1.4

- content/en/docs/corda-enterprise/4.6/operations/deployment/deployment-kubernetes.md
The correct name of the Docker image of `cenm-cli` is `corda/enterprise-cenm-cli`. If the user runs `docker pull cenm-cli`, he will get the following error and so create confusion:
```
Error response from daemon: pull access denied for cenm-cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
> Fix the Docker image name of cenm-cli

- content/en/docs/cenm/1.4/deployment-kubernetes.md
In order to successfully start the pods in the k8s cluster, the user has to set the storage class type accordingly with the cloud provider in use (Azure or AWS).
Without it, the pods will be stuck in a _pending_ status forever and the user will see this error:
`0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`
Related to EG-4578.
> EG-4578 Add k8s storage class configuration

- content/en/docs/corda-enterprise/4.6/node/operating/querying-flow-data.md
EG-4500 [ENT-6012] Update 'Querying flow data' doc page clarifying that the multi-RPC client should be aligned with the node version
> EG-4500 [ENT-6012] Update 'Querying flow data' doc page clarifying that the multi-RPC client should be aligned with the node version

- content/en/docs/corda-os/4.7/tutorial-contract.md
For those following the tutorial we want to include that import to make it clearer to them where the sumCashBy is coming from in this java example of the contracts tutorial here: https://docs.corda.net/docs/corda-os/4.7/tutorial-contract.html#checking-the-requirements
This is based on my interaction with Andrea d'Auria here : https://cordaledger.slack.com/archives/C2KGD72UX/p1609865285066000 
He also kindly outlined he needed to add another jar in order for him to continue to follow the tutorial. 
not sure if you'd like to add this as well. 
```
cordaCompile "$corda_release_group:corda-finance-contracts:$corda_release_version"
```
thanks
> adding an import

- content/en/docs/corda-os/4.7/event-scheduling.md
- content/en/docs/corda-os/4.7/flow-state-machines.md
- content/en/docs/corda-os/4.7/flow-testing.md
- content/en/docs/corda-os/4.7/tut-two-party-contract.md
- content/en/docs/corda-os/4.7/tutorial-attachments.md
- content/en/docs/corda-os/4.7/tutorial-contract.md
- content/en/docs/corda-os/4.7/tutorial-observer-nodes.md
Raising this PR to add missing code snippets in OS 4.7 tutorials. 
@peterli-r3 , in `tutorial-observer-nodes.md` under the "Adding support for observer nodes" section can you look closely at the last paragraphs following the code snippets? The sample linked there should be removed, and the text doesn't apply either, but would it make sense to update this text to provide descriptions/explanation of the flows in the new code snippets?
> EG-3921: Added missing code snippets to OS 4.7 tutorials

- content/en/docs/apps/bankinabox/user-interface/how-to.md
- content/en/docs/apps/bankinabox/user-interface/user-interface.md
- themes/hugo-r3-theme/layouts/index.html
Previously this was "How to guide", corrected to "How-to guide" according to Microsoft style guide.
> EG-4668: Changed BIAB guide name to How-to guide in all instances.

- content/en/docs/corda-os/4.4/building-the-docs.md
- content/en/docs/corda-os/4.5/building-the-docs.md
- content/en/docs/corda-os/4.6/building-the-docs.md
- content/en/docs/corda-os/4.7/building-the-docs.md
@edward-prosser , @ivanterziev-r3 Could you take a look at this PR? Updating the Build the docs page in our OS docs to reflect some missing steps and examples. It would be great if you could look closely at added examples and commands to be sure they are correct and clear.
> EG-4699: Added some missing steps, examples, updated version numbers listed.

- content/en/docs/corda-enterprise/4.0/clientrpc.md
- content/en/docs/corda-enterprise/4.1/clientrpc.md
- content/en/docs/corda-enterprise/4.2/clientrpc.md
- content/en/docs/corda-enterprise/4.3/clientrpc.md
- content/en/docs/corda-enterprise/4.4/node/operating/clientrpc.md
- content/en/docs/corda-enterprise/4.5/node/operating/clientrpc.md
- content/en/docs/corda-enterprise/4.6/node/operating/clientrpc.md
- content/en/docs/corda-enterprise/4.7/node/operating/clientrpc.md
- content/en/docs/corda-os/4.0/clientrpc.md
- content/en/docs/corda-os/4.1/clientrpc.md
- content/en/docs/corda-os/4.3/clientrpc.md
- content/en/docs/corda-os/4.4/clientrpc.md
- content/en/docs/corda-os/4.5/clientrpc.md
- content/en/docs/corda-os/4.6/clientrpc.md
- content/en/docs/corda-os/4.7/clientrpc.md
Adding documentation on fixing RPC permissions (DOC-1693) and also adding fixes to the OS documentation that should have been added as part of DOC-875 and ENT-4825.
> DOC-1693: adding documentation on fixing RPC permissions

- content/en/docs/corda-enterprise/4.6/secrets.md
- content/en/docs/corda-enterprise/4.7/secrets.md
* DOC-1810 Fixed a typo CE 4.6/4.7 Corda secrets pages.
* Resolving issue corda/corda-docs#415.
> DOC-1810 Fixed a typo in CE 4.6/4.7 Corda secrets pages

- content/en/docs/corda-os/4.4/contributing-philosophy.md
- content/en/docs/corda-os/4.4/contributing.md
- content/en/docs/corda-os/4.5/contributing-philosophy.md
- content/en/docs/corda-os/4.5/contributing.md
- content/en/docs/corda-os/4.6/contributing-philosophy.md
- content/en/docs/corda-os/4.6/contributing.md
- content/en/docs/corda-os/4.7/contributing-philosophy.md
- content/en/docs/corda-os/4.7/contributing.md
DOC-101 Fixed links to contributors lists in github for OS 4.4/4.7
> DOC-101 Fixed links to contributors lists in github for OS 4.4/4.7

- content/en/docs/corda-enterprise/4.7/node/management-console/index.md
- content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
- content/en/docs/corda-enterprise/4.8/node/management-console/index.md
- content/en/docs/corda-enterprise/4.8/node/node-flow-management-console.md
DOC-2077 Fixes to front matter and file name of the node management console page, and the front matter of the flow management console page for CE 4.7 and 4.8
> DOC-2077 Fixes to node management console & flow management console pages
